# Generated by Django 5.2.4 on 2025-07-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='release_year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
